name: Docs

on:
  # Update on pushes to main
  push:
    branches: [ "main" ]
    paths:
      - "turbospork/include/**"

  # Allow running workflow manually
  workflow_dispatch:

# Restrict permissions to just Github Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Only run one at a time, but don't cancel in-progress deployments
concurrency:
  group: "pages"
  cancel-in-progress: false
    
jobs:
  # Build the site and publish an artifact
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Building docs
        uses: mattnotmitt/doxygen-action@1.9.5
        with:
          doxyfile-path: docs/Doxyfile
          enable-latex: false
          
      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: "docs/html"

  # Download build's artifact and publish site
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v2
